### ISSUE TITLE
Change/feature request (UI)

### ISSUE THREAD

**Issue by HA-TB303** [DomiStyle/esphome-panasonic-ac#14]
HI, I noticed the Panasonic (cloud based) integration and this one differ quit substantially.
It would be great if the integration could be more in line with the "official" integration.
Some functions are missing, some are substantially different:

Cloud based integration -- VS -- esphome integration:

Practically the same and all good:
![image](https://user-images.githubusercontent.com/9609805/128167867-7d1f816b-620b-4e83-8e8a-4a707f5349ae.png)

No ECO mode, or just a different name?
![image](https://user-images.githubusercontent.com/9609805/128167974-78f96555-1cb6-4fe6-8667-c9967b5e83c8.png)

No fan mode?
![image](https://user-images.githubusercontent.com/9609805/128168054-345f5c30-55dd-475b-aa38-e987d5957103.png)

Positioning the fan is not possible? / my unit only has a vertical swing.
![image](https://user-images.githubusercontent.com/9609805/128168107-4ec677f9-5fc7-4f4f-b719-16268b9b750d.png)

Separate switches and sensors, for stuff that might be able to live in the climate component? (I really don't know it that is possible.....
![image](https://user-images.githubusercontent.com/9609805/128168575-df232a03-59ba-4f6d-883c-684183f18c0c.png)

**Comment by DomiStyle** [comment]
Please see the readme on the dev branch: https://github.com/DomiStyle/esphome-panasonic-ac/tree/dev-cztacg1
Things have changed quite a bit. All of the options are identical to the Comfort Cloud options but they might look slightly different depending on the exact model since Panasonic likes to shift stuff around.

> No ECO mode, or just a different name?

Eco mode is exposed as sensor, see https://github.com/DomiStyle/esphome-panasonic-ac/tree/dev-cztacg1#setting-supported-features

> No fan mode?

Fan modes require the dev branch, ESPHome 1.20.0+ and Home Assistant 2021.8.0+ (released today).

> Positioning the fan is not possible? / my unit only has a vertical swing.

See https://github.com/DomiStyle/esphome-panasonic-ac/tree/dev-cztacg1#adding-manual-swing-selection-to-home-assistant

They will be exposed as select soon instead of input_select which makes them auto discoverable in Home Assistant. However, this change has not made it into the latest ESPHome version so far.

> Separate switches and sensors, for stuff that might be able to live in the climate component? (I really don't know it that is possible.....

It's not possible to modify the ESPHome climate component, they have to be exposed as switches and sensors.

**Comment by sygys** [comment]
I contacted esphome on the matter of the swing mode I left I understand correct esphome allready supports swing mode and this is up to the home assistant part of esp to support it. It would be really great of we had swing mode in a different way then a text sensor. This really is a pain when combining it with other commands in an automation. The ac is going all over the place when you change the swing mode and then put in another command just behind that one. Cool heat auto and dry all can happen then. I can imagine this could eventually even crash the AC.
