### ISSUE TITLE
MQTT control

### ISSUE THREAD

**Issue by olivr2s** [DomiStyle/esphome-panasonic-ac#71]
Hello,   _(Google traduction - French to English)_

I followed the instructions correctly and connected an ESP32 instead of my CZ-TACG1 Wi-Fi module to have my air conditioning with MQTT.
It works fine, I have all the information going back to MQTT Explorer.
![image](https://user-images.githubusercontent.com/59806634/198388227-0c7bb208-2d0e-4707-8eee-9ef5d122fdba.png)

On the other hand, to send a command to my air conditioning, nothing works.
The only command that works is when the air conditioning is already on and I send the "off" command and the air conditioning stops.

To send a command I use:

Topic `clim-parents-mqtt/climate/clim_parents_mqtt/mode/command`  and RAW `off`

If I use the air conditioning remote control, I have the modes changing in `state`, but if I use the same values to send a command like `cool`, nothing happens even if in topic `debug` I see pass `COOL`

An idea to manage to send a command via MQTT to the air conditioning except `off`

**Comment by hansf71** [comment]
> Hello, _(Google traduction - French to English)_
> 
> I followed the instructions correctly and connected an ESP32 instead of my CZ-TACG1 Wi-Fi module to have my air conditioning with MQTT. It works fine, I have all the information going back to MQTT Explorer. ![image](https://user-images.githubusercontent.com/59806634/198388227-0c7bb208-2d0e-4707-8eee-9ef5d122fdba.png)
> 
> On the other hand, to send a command to my air conditioning, nothing works. The only command that works is when the air conditioning is already on and I send the "off" command and the air conditioning stops.
> 
> To send a command I use:
> 
> Topic `clim-parents-mqtt/climate/clim_parents_mqtt/mode/command` and RAW `off`
> 
> If I use the air conditioning remote control, I have the modes changing in `state`, but if I use the same values to send a command like `cool`, nothing happens even if in topic `debug` I see pass `COOL`
> 
> An idea to manage to send a command via MQTT to the air conditioning except `off`

Hi, I am also using mqtt to control my Panasonic ac. Have you tried to send retained mqtt messages? So far, to me, it looks like thats the only way to be sure a command is executed correctly. After a slight delay the ESP connects to the mqtt server and receives the retained message. It looks like messages without the retain flag get lost due to the ESP keeps connecting and disconnecting to the mqtt server.
A drawback to the retained messages is the remote control not working. Because the retained messages stay on the mqtt server until you erase them, Any remote control actions are after a short while overwritten by previous sent mqtt messages.
Let me hear about your results.
Greetings,
Hansf71
